import { Inter } from "next/font/google";
import "./globals.css";
import ProviderApollo from "@/components/apolloProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import WrapperComponent from "@/components/WrapperComponent";
import { Provider } from "react-redux";
import { store } from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderApollo>
          {/* <Provider store={store}> */}
            <WrapperComponent>{children}</WrapperComponent>
          {/* </Provider> */}
        </ProviderApollo>
        <ToastContainer />
      </body>
    </html>
  );
}
